[2021-01-19 05:25:29,037] SEVERE {b7a.log.crash} - error("malformed URL: api.openweathermap.org") 
org.ballerinalang.test.runtime.exceptions.BallerinaTestException: error("malformed URL: api.openweathermap.org")
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:120)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:54)
	at org.ballerinalang.test.runtime.BTestRunner.startSuite(BTestRunner.java:565)
	at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:285)
	at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:107)
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:75)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:61)
	at org.ballerinalang.test.runtime.Main.main(Main.java:53)
Caused by: error("malformed URL: api.openweathermap.org")
	at io.ballerina.runtime.api.creators.ErrorCreator.createDistinctError(ErrorCreator.java:167)
	at io.ballerina.runtime.api.creators.ErrorCreator.createDistinctError(ErrorCreator.java:151)
	at org.ballerinalang.net.http.HttpUtil.createHttpError(HttpUtil.java:565)
	at org.ballerinalang.net.http.clientendpoint.CreateSimpleHttpClient.createSimpleHttpClient(CreateSimpleHttpClient.java:65)
	at ballerina.http.1_0_4.http_client_endpoint.createSimpleHttpClient(http_client_endpoint.bal:351)
	at ballerina.http.1_0_4.$value$HttpClient.init(http_client.bal:38)
	at ballerina.http.1_0_4.$value$HttpClient.call(http_client.bal)
	at ballerina.http.1_0_4.$value$HttpClient.$init$(http_client.bal:25)
	at ballerina.http.1_0_4.$value$HttpClient.call(http_client.bal)
	at ballerina.http.1_0_4.http_client.createClient(http_client.bal:285)
	at ballerina.http.1_0_4.http_secure_client.createHttpSecureClient(http_secure_client.bal:314)
	at ballerina.http.1_0_4.$value$HttpCachingClient.init(caching_http_caching_client.bal:44)
	at ballerina.http.1_0_4.$value$HttpCachingClient.call(caching_http_caching_client.bal)
	at ballerina.http.1_0_4.$value$HttpCachingClient.$init$(caching_http_caching_client.bal:27)
	at ballerina.http.1_0_4.$value$HttpCachingClient.call(caching_http_caching_client.bal)
	at ballerina.http.1_0_4.caching_http_caching_client.createHttpCachingClient(caching_http_caching_client.bal:307)
	at ballerina.http.1_0_4.http_client_endpoint.createDefaultClient(http_client_endpoint.bal:615)
	at ballerina.http.1_0_4.http_client_endpoint.createCookieClient(http_client_endpoint.bal:610)
	at ballerina.http.1_0_4.http_client_endpoint.checkForRetry(http_client_endpoint.bal:515)
	at ballerina.http.1_0_4.http_client_endpoint.initialize(http_client_endpoint.bal:485)
	at ballerina.http.1_0_4.$value$Client.init(http_client_endpoint.bal:57)
	at ballerina.http.1_0_4.$value$Client.call(http_client_endpoint.bal)
	at ballerina.http.1_0_4.$value$Client.$init$(http_client_endpoint.bal:35)
	at ballerina.http.1_0_4.$value$Client.call(http_client_endpoint.bal)
	at nuwant.exercise5.0_1_0.$value$Client.init(main.bal:23)
	at nuwant.exercise5.0_1_0.$value$Client.call(main.bal)
	at nuwant.exercise5.0_1_0.$value$Client.$init$(main.bal:16)
	at nuwant.exercise5.0_1_0.$value$Client.call(main.bal)
	at nuwant.exercise5.0_1_0.exercise5.$gen$nuwant$0047exercise5$00580$00461$00460$0046$0060init$00620(exercise5:10)
	at nuwant.exercise5.0_1_0.exercise5.$gen$$0046$0060testinit$0062(exercise5:4)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:107)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:546)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:283)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:251)
	at java.base/java.lang.Thread.run(Unknown Source)
 
[2021-01-19 05:33:03,476] SEVERE {b7a.log.crash} - there are test failures 
java.lang.RuntimeException: there are test failures
	at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:78)
	at org.ballerinalang.test.runtime.Main.startTestSuit(Main.java:61)
	at org.ballerinalang.test.runtime.Main.main(Main.java:53)
 
